// File: ROM.v
// Generated by MyHDL 0.11
// Date: Tue Jun 22 21:48:07 2021


`timescale 1ns/10ps

module ROM (
    mem_write,
    data_in,
    PC,
    INST_OUt
);


input mem_write;
input [31:0] data_in;
input [31:0] PC;
output [31:0] INST_OUt;
wire [31:0] INST_OUt;

wire [31:0] ADDR;
wire [7:0] DATA_OUT_1;
wire [7:0] DATA_OUT_2;
wire [7:0] DATA_OUT_3;
wire [7:0] DATA_OUT_4;
reg [7:0] Memory_block0_MemoryBank0_memory [0:32-1];
reg [7:0] Memory_block0_MemoryBank1_memory [0:32-1];
reg [7:0] Memory_block0_MemoryBank2_memory [0:32-1];
reg [7:0] Memory_block0_MemoryBank3_memory [0:32-1];




assign ADDR = (PC >>> 2);



assign DATA_OUT_1 = Memory_block0_MemoryBank0_memory[ADDR];


always @(posedge mem_write) begin: ROM_MEMORY_BLOCK0_MEMORYBANK0_WRITE
    Memory_block0_MemoryBank0_memory[ADDR] <= data_in;
end



assign DATA_OUT_2 = Memory_block0_MemoryBank1_memory[ADDR];


always @(posedge mem_write) begin: ROM_MEMORY_BLOCK0_MEMORYBANK1_WRITE
    Memory_block0_MemoryBank1_memory[ADDR] <= data_in;
end



assign DATA_OUT_3 = Memory_block0_MemoryBank2_memory[ADDR];


always @(posedge mem_write) begin: ROM_MEMORY_BLOCK0_MEMORYBANK2_WRITE
    Memory_block0_MemoryBank2_memory[ADDR] <= data_in;
end



assign DATA_OUT_4 = Memory_block0_MemoryBank3_memory[ADDR];


always @(posedge mem_write) begin: ROM_MEMORY_BLOCK0_MEMORYBANK3_WRITE
    Memory_block0_MemoryBank3_memory[ADDR] <= data_in;
end



assign INST_OUt = {DATA_OUT_4, DATA_OUT_3, DATA_OUT_2, DATA_OUT_1};

endmodule
