// File: SBA_DECODER.v
// Generated by MyHDL 0.11
// Date: Tue Jun 22 21:47:36 2021


`timescale 1ns/10ps

module SBA_DECODER (
    STB_I,
    ADDR_I,
    STB_O
);


input [3:0] STB_I;
input [31:0] ADDR_I;
output [8:0] STB_O;
reg [8:0] STB_O;




always @(ADDR_I, STB_I) begin: SBA_DECODER_DECODE
    if (STB_I[0]) begin
        if ((ADDR_I <= 1023)) begin
            STB_O = {6'h1, STB_I[4-1:1]};
        end
        else if ((ADDR_I == 1024)) begin
            STB_O = {6'h2, STB_I[4-1:1]};
        end
        else if ((ADDR_I == 1025)) begin
            STB_O = {6'h4, STB_I[4-1:1]};
        end
        else if ((ADDR_I == 1026)) begin
            STB_O = {6'h8, STB_I[4-1:1]};
        end
        else if ((ADDR_I == 1027)) begin
            STB_O = {6'h10, 3'h0};
        end
        else if ((ADDR_I == 1028)) begin
            STB_O = {6'h10, 3'h1};
        end
        else if ((ADDR_I == 1029)) begin
            STB_O = {6'h10, 3'h2};
        end
        else if ((ADDR_I == 1030)) begin
            STB_O = {6'h20, STB_I[4-1:1]};
        end
    end
    else begin
        STB_O = 0;
    end
end

endmodule
